# Tests for src.workflow_audit.history_parser's `session` column -- counts
# process restarts (invoke.py's "=== Session started at ... ===" banner,
# written unconditionally on every launch) without disturbing the existing
# round/agent parsing.
#
# Also covers the wait_for_update outcome/duration columns (wait_status,
# wait_minutes): distinguishing a genuine wait (with or without updates) from
# an outright refusal, and recovering how long a genuine wait actually lasted.

import pandas as pd

from src.disposition_messages import (
    MSG_NOTHING_TO_WAIT_FOR,
    format_wait_gate1_refusal,
    format_wait_gate2_refusal,
)
from src.workflow_audit.history_parser import _parse_wait_result, parse_history

_ROUND_1 = """supervisor is processing!!!!! Current time: 0:00:01.
  inspect_my_canvas (toolu_1
Name: inspect_my_canvas

ok
"""
_ROUND_2 = """Agent OER_Agent is processing!!!!!
  arXiv_search (toolu_2
Name: arXiv_search

ok
"""
_ROUND_3 = """supervisor is processing!!!!! Current time: 0:10:00.
  query_explog (toolu_3
Name: query_explog

ok
"""
_BANNER_1 = "=== Session started at 2026-01-01 00:00:00 ===\n\n"
_BANNER_2 = "=== Session started at 2026-01-01 01:00:00 ===\n\n"


def test_leading_banner_is_session_1_not_2(tmp_path):
    # Real his.txt files almost always open with a banner (invoke.py writes
    # it as literally the first line) -- that must NOT be treated as a
    # restart; the rounds after it are session 1, not a phantom session 2.
    p = tmp_path / "his.txt"
    p.write_text(_BANNER_1 + _ROUND_1 + _ROUND_2 + _BANNER_2 + _ROUND_3)
    df = parse_history(p, progress=False)
    assert list(df["session"]) == [1, 1, 2]
    assert list(df["round"]) == [1, 2, 3]


def test_midstream_banner_still_bumps_without_a_leading_one(tmp_path):
    # No leading banner (e.g. a legacy his.txt from before this banner
    # existed) -- a later banner must still mark a real restart boundary.
    p = tmp_path / "his.txt"
    p.write_text(_ROUND_1 + _ROUND_2 + _BANNER_2 + _ROUND_3)
    df = parse_history(p, progress=False)
    assert list(df["session"]) == [1, 1, 2]


def test_no_banner_at_all_is_a_single_session(tmp_path):
    p = tmp_path / "his.txt"
    p.write_text(_ROUND_1 + _ROUND_2 + _ROUND_3)
    df = parse_history(p, progress=False)
    assert list(df["session"]) == [1, 1, 1]


def test_back_to_back_banners_with_no_round_between_them(tmp_path):
    # A process that crashes before writing even one round marker: two
    # banners in a row produce no row for the short-lived session, but the
    # next real row correctly carries the LATER session number.
    p = tmp_path / "his.txt"
    p.write_text(_BANNER_1 + _ROUND_1 + _BANNER_2 + _BANNER_2 + _ROUND_2)
    df = parse_history(p, progress=False)
    assert list(df["session"]) == [1, 3]


# ===========================================================================
# wait_for_update outcome/duration: wait_status ("waited"/"timeout"/"refused")
# and wait_minutes. Real text is the literal f-strings from the two
# "genuinely waited" return paths in src/tools.py's wait_for_update
# (confirmed present verbatim in production_run_27-05-2026_fork_16_07_2026's
# hist/his_1.txt and legacy his.txt). Refusal text is generated by calling
# the actual current src.disposition_messages functions rather than
# hand-copied, so these fixtures can't drift out of sync with the real
# messages (Gate 2's wording was reworked after the fork's logs were
# written -- calling the real function sidesteps that entirely).
# ===========================================================================

# Both embed a real "\n" (the tool's own f-string splits after the number),
# so the file genuinely has 2 physical lines here, same as production -- rule
# 6b only ever captures the first one, hence .splitlines()[0] in the unit
# tests below (that's the exact contract _parse_wait_result is called under).
_WAITED_TEXT = (
    "Total time elapsed since project start 9 days, 14:25:02.842504, "
    "time waited: 1hours and 51 minutes.\n"
    " Here are the updates while you are waiting: "
)
_WAITED_ZERO_HOURS_TEXT = (
    "Total time elapsed since project start 9 days, 15:06:58.603300, "
    "time waited: 0hours and 37 minutes.\n"
    " Here are the updates while you are waiting: "
)
_WAITED_ZERO_MINUTES_TEXT = (
    "Total time elapsed since project start 1 day, 2:00:00.000000, "
    "time waited: 2hours and 0 minutes.\n"
    " Here are the updates while you are waiting: "
)
_TIMEOUT_TEXT = (
    "Total time elapsed since project start 4 days, 15:43:11.609488, you "
    "have been waiting for 240 minutes with no update in the EXPLOG. You "
    "may want to check the EXPLOG and see if there is anything you can do "
    "to move the study forward."
)


def _wait_round(marker: str, result_text: str) -> str:
    """One round: `marker` starts it, then a single wait_for_update call
    whose result is `result_text` (mirrors the real pretty-printed
    Tool-Calls/Name/blank-line/content shape rule 4/6a/6b expect)."""
    return (
        f"{marker}\n"
        "  wait_for_update (toolu_w\n"
        "Name: wait_for_update\n\n"
        f"{result_text}\n"
    )


# ---- unit tests: _parse_wait_result in isolation ----

def test_parse_wait_result_waited():
    assert _parse_wait_result(_WAITED_TEXT.splitlines()[0]) == ("waited", 111)


def test_parse_wait_result_waited_zero_hours():
    assert _parse_wait_result(_WAITED_ZERO_HOURS_TEXT.splitlines()[0]) == ("waited", 37)


def test_parse_wait_result_waited_zero_minutes():
    assert _parse_wait_result(_WAITED_ZERO_MINUTES_TEXT.splitlines()[0]) == ("waited", 120)


def test_parse_wait_result_timeout():
    assert _parse_wait_result(_TIMEOUT_TEXT.splitlines()[0]) == ("timeout", 240)


def test_parse_wait_result_refused_gate1():
    text = format_wait_gate1_refusal(["matA", "matB"])
    assert _parse_wait_result(text.splitlines()[0]) == ("refused", None)


def test_parse_wait_result_refused_gate2_path_a():
    # Path A: ready/forgotten work exists -> the worker-submits-itself message.
    text = format_wait_gate2_refusal(
        [{"candidate_id": "matA", "kind": "bulk"}], running_count=7, pending_count=4,
    )
    assert _parse_wait_result(text.splitlines()[0]) == ("refused", None)


def test_parse_wait_result_refused_gate2_path_b():
    # Path B: queue below floor, nothing ready -> supervisor-handback message.
    text = format_wait_gate2_refusal([], running_count=2, pending_count=3)
    assert _parse_wait_result(text.splitlines()[0]) == ("refused", None)


def test_parse_wait_result_refused_nothing_to_wait():
    assert _parse_wait_result(MSG_NOTHING_TO_WAIT_FOR.splitlines()[0]) == ("refused", None)


# ---- integration tests: through parse_history() ----

def test_wait_row_gets_waited_status_and_minutes(tmp_path):
    p = tmp_path / "his.txt"
    p.write_text(_wait_round("Agent OER_Agent is processing!!!!!", _WAITED_TEXT))
    df = parse_history(p, progress=False)
    row = df[df.tool == "wait_for_update"].iloc[0]
    assert row.wait_status == "waited"
    assert row.wait_minutes == 111


def test_wait_row_gets_timeout_status_and_minutes(tmp_path):
    p = tmp_path / "his.txt"
    p.write_text(_wait_round("Agent OER_Agent is processing!!!!!", _TIMEOUT_TEXT))
    df = parse_history(p, progress=False)
    row = df[df.tool == "wait_for_update"].iloc[0]
    assert row.wait_status == "timeout"
    assert row.wait_minutes == 240


def test_wait_row_gets_refused_status_and_null_minutes(tmp_path):
    p = tmp_path / "his.txt"
    refusal = format_wait_gate1_refusal(["matA"])
    p.write_text(_wait_round("Agent OER_Agent is processing!!!!!", refusal))
    df = parse_history(p, progress=False)
    row = df[df.tool == "wait_for_update"].iloc[0]
    assert row.wait_status == "refused"
    assert pd.isna(row.wait_minutes)


def test_non_wait_tool_rows_have_blank_wait_columns(tmp_path):
    p = tmp_path / "his.txt"
    p.write_text(
        "supervisor is processing!!!!! Current time: 0:00:01.\n"
        "  query_explog (toolu_q\n"
        "Name: query_explog\n\n"
        "ok\n"
    )
    df = parse_history(p, progress=False)
    row = df[df.tool == "query_explog"].iloc[0]
    assert row.wait_status == ""
    assert pd.isna(row.wait_minutes)


def test_multiple_wait_calls_get_independent_statuses(tmp_path):
    # Guards against `open_call` state leaking between successive tool calls:
    # a refused call followed by a genuine wait must not blend their results.
    p = tmp_path / "his.txt"
    p.write_text(
        _wait_round("Agent OER_Agent is processing!!!!!", format_wait_gate1_refusal(["matA"]))
        + _wait_round("Agent OER_Agent is processing!!!!!", _WAITED_TEXT)
    )
    df = parse_history(p, progress=False)
    waits = df[df.tool == "wait_for_update"]
    assert list(waits.wait_status) == ["refused", "waited"]
    assert pd.isna(waits.wait_minutes.iloc[0])
    assert waits.wait_minutes.iloc[1] == 111


def test_empty_round_placeholder_has_blank_wait_columns(tmp_path):
    p = tmp_path / "his.txt"
    p.write_text(
        "supervisor is processing!!!!! Current time: 0:00:01.\n"  # round 1: no tool calls
        "Agent OER_Agent is processing!!!!!\n"
        "supervisor is processing!!!!! Current time: 0:05:00.\n"
        "  query_explog (toolu_q\n"
        "Name: query_explog\n\n"
        "ok\n"
    )
    df = parse_history(p, progress=False)
    placeholder = df[(df["round"] == 1) & (df["tool"] == "")]
    assert len(placeholder) == 1
    assert placeholder.iloc[0].wait_status == ""
    assert pd.isna(placeholder.iloc[0].wait_minutes)
