## Environment variables
ANTHROPIC_API_KEY: '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'
ANTHROPIC_MODEL: "claude-3-7-sonnet-20250219"


# Pseudo potential path
PSEUDO_DIR: '/nfs/turbo/coe-venkvis/ziqiw-turbo/material_agent/all_lda_pbe_UPF'
# PSEUDO_DIR: '/nfs/turbo/coe-venkvis/ziqiw-turbo/sssp'

# Working directory
# WORKING_DIR: '/nfs/turbo/coe-venkvis/ziqiw-turbo/material_agent/LDAProdNoReflecout'
WORKING_DIR: '/nfs/turbo/coe-venkvis/ziqiw-turbo/material_agent/BEEFtry3out'

SAVE_DIALOGUE: 'True'