## Environment variables
ANTHROPIC_API_KEY:  'key'
LANGSIM_PROVIDER: "anthropic" 
LANGSIM_API_KEY: 'key'
LANGSIM_MODEL: "claude-3-5-sonnet-20240620"


# Pseudo potential path
PSEUDO_DIR: '/nfs/turbo/coe-venkvis/hongshuh/material_agent/SSSP_1.3.0_PBE_precision'


# Working directory
WORKING_DIR: '/nfs/turbo/coe-venkvis/hongshuh/material_agent/out'