## Environment variables
hongshuo_ANTHROPIC_API_KEY: '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'
ANTHROPIC_API_KEY: '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'
ANTHROPIC_MODEL: "claude-3-7-sonnet-20250219"

OpenAI_API_KEY: 'DyCi96iYOkjngoL3s7DADttMI4ebknxgNiyLugne0JaQR0kV9En2JQQJ99BBACHYHv6XJ3w3AAAAACOGkOHG'
OpenAI_BASE_URL: "https://ai-awadell6407ai595196234123.services.ai.azure.com/"
OpenAI_MDL: "gpt-4o"

DeepSeek_API_KEY: 'aVtbzLs42hQ6a44XhFp4R9wkEQ3hpvzw'
DeepSeek_BASE_URL: "https://DeepSeek-R1-bglig.eastus2.models.ai.azure.com"
DeepSeek_MDL: "DeepSeek-R1"



# Pseudo potential path
PSEUDO_DIR: '/nfs/turbo/coe-venkvis/ziqiw-turbo/material_agent/all_lda_pbe_UPF'


# Working directory
WORKING_DIR: '/nfs/turbo/coe-venkvis/ziqiw-turbo/material_agent/out'

SAVE_DIALOGUE: 'True'