## Environment variables
ANTHROPIC_API_KEY:  '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'
LANGSIM_PROVIDER: "anthropic" 
LANGSIM_API_KEY: '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'
LANGSIM_MODEL: "claude-3-5-sonnet-20240620"


# Pseudo potential path
pseudo_dir: '/Users/hongshuh/Desktop/LLM/scifm-comp/SSSP_1.3.0_PBE_precision'